### ISSUE TITLE
Publish to mvncentral

### ISSUE THREAD

**Issue by isnikulin** [pelenthium/clickhouse-dialect-spring-boot-starter#3]
Heyo, with bintray being deprecated, any attempt to fetch this dependency with maven gives 403 error.

Would it be possible to push this dependency to the maven central? 
Thanks in advance!

**Comment by pelenthium** [comment]
Published to maven central
https://mvnrepository.com/artifact/io.github.pelenthium/clickhouse-dialect-spring-boot-starter
